[2024-11-02T20:57:39.067+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-02T20:57:39.082+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: job_scraping_pipeline.scrape_chunk_2 manual__2024-11-02T10:18:09.096740+00:00 [None]>
[2024-11-02T20:57:39.092+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: job_scraping_pipeline.scrape_chunk_2 manual__2024-11-02T10:18:09.096740+00:00 [None]>
[2024-11-02T20:57:39.092+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 5
[2024-11-02T20:57:39.109+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): scrape_chunk_2> on 2024-11-02 10:18:09.096740+00:00
[2024-11-02T20:57:39.123+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'job_scraping_pipeline', 'scrape_chunk_2', 'manual__2024-11-02T10:18:09.096740+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpchtzelkx']
[2024-11-02T20:57:39.126+0000] {standard_task_runner.py:105} INFO - Job 55: Subtask scrape_chunk_2
[2024-11-02T20:57:39.128+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=236) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-02T20:57:39.128+0000] {standard_task_runner.py:72} INFO - Started process 241 to run task
[2024-11-02T20:57:39.173+0000] {task_command.py:467} INFO - Running <TaskInstance: job_scraping_pipeline.scrape_chunk_2 manual__2024-11-02T10:18:09.096740+00:00 [running]> on host 6fb5d61061dc
[2024-11-02T20:57:39.253+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='job_scraping_pipeline' AIRFLOW_CTX_TASK_ID='scrape_chunk_2' AIRFLOW_CTX_EXECUTION_DATE='2024-11-02T10:18:09.096740+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-02T10:18:09.096740+00:00'
[2024-11-02T20:57:39.254+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-02T20:57:39.275+0000] {main_scrap.py:56} INFO - 初始化完成，輸出目錄: jobs_csv
[2024-11-02T20:57:39.275+0000] {main_scrap.py:94} INFO - 開始爬取關鍵字: 資料科學家
[2024-11-02T20:57:39.276+0000] {main_scrap.py:77} INFO - 請求URL: https://www.104.com.tw/jobs/search/?ro=0&kwop=7&keyword=%E8%B3%87%E6%96%99%E7%A7%91%E5%AD%B8%E5%AE%B6&order=15&asc=0&page=1&mode=s&jobsource=m_joblist_search&searchTempExclude=2
[2024-11-02T20:57:39.847+0000] {main_scrap.py:107} INFO - 開始爬取關鍵字: 資料科學家, 共有：24 頁
[2024-11-02T20:57:39.854+0000] {logging_mixin.py:190} WARNING - 爬取 資料科學家:   0%|          | 0/24 [00:00<?, ?it/s]
[2024-11-02T20:57:39.855+0000] {main_scrap.py:112} INFO - 頁面 1 延遲 13.84 秒
[2024-11-02T20:57:49.232+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-11-02T20:57:49.233+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-02T20:57:49.235+0000] {process_utils.py:132} INFO - Sending 15 to group 241. PIDs of all processes in the group: [241]
[2024-11-02T20:57:49.235+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 241
[2024-11-02T20:57:49.236+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-02T20:57:49.236+0000] {logging_mixin.py:190} WARNING - 爬取 資料科學家:   0%|          | 0/24 [00:09<?, ?it/s]
[2024-11-02T20:57:49.242+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/tasks/main_scrap.py", line 264, in web_crawler
    scraper.scrape_jobs(key_txt)
  File "/opt/airflow/tasks/main_scrap.py", line 113, in scrape_jobs
    time.sleep(sleep_time)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-11-02T20:57:49.248+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=job_scraping_pipeline, task_id=scrape_chunk_2, run_id=manual__2024-11-02T10:18:09.096740+00:00, execution_date=20241102T101809, start_date=20241102T205739, end_date=20241102T205749
[2024-11-02T20:57:49.261+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-02T20:57:49.288+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=241, status='terminated', exitcode=2, started='20:57:38') (241) terminated with exit code 2
